version: '3.8'

services:
  app:
    container_name: shopping-cart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Client app
      - "3001:3001"  # API server
